# Generated by Django 4.2 on 2023-05-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(db_column='flight number', max_length=128)),
                ('origin_country', models.CharField(db_column='origin country', max_length=128)),
                ('origin_city', models.CharField(db_column='origin city', max_length=128)),
                ('origin_airport_code', models.CharField(db_column='origin airport code', max_length=128)),
                ('destination_country', models.CharField(db_column='destination country', max_length=128)),
                ('destination_city', models.CharField(db_column='destination_city', max_length=128)),
                ('destination_airport_code', models.CharField(db_column='destination airport code', max_length=128)),
            ],
            options={
                'db_table': 'flights',
            },
        ),
    ]
