# Generated by Django 4.2 on 2023-06-01 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_flights_app', '0002_order_flight_available_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flight_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mini_flights_app.flight'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(db_column='order date'),
        ),
    ]
