# Generated by Django 4.2 on 2023-06-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_flights_app', '0003_order_flight_id_alter_order_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='flight_id',
            new_name='flight',
        ),
    ]
